// Type Imports
import type { UsersType } from '@/types/apps/userTypes'

export const db: UsersType[] = [
  {
    "id": 1,
    "fullName": "Tendai Moyo",
    "company": "Yotz PVT LTD",
    "role": "Agritext Officer",
    "username": "gslixby0",
    "country": "El Salvador",
    "contact": "(479) 232-9151",
    "email": "gslixby0@abc.net.au",
    "currentPlan": "Harare",
    "status": "inactive",
    "avatar": "",
    "avatarColor": "primary",
    "billing": 45
  },
  {
    "id": 2,
    "fullName": "Nyasha Chikwanje",
    "company": "Yotz PVT LTD",
    "role": "Agritext Officer",
    "username": "jzsmith1",
    "country": "El Salvador",
    "contact": "(479) 232-9152",
    "email": "jzsmith1@abc.net.au",
    "currentPlan": "Bulawayo",
    "status": "inactive",
    "avatar": "",
    "avatarColor": "primary",
    "billing": 32
  },
  {
    "id": 3,
    "fullName": "Kudzai Ndlovu",
    "company": "Yotz PVT LTD",
    "role": "Agritext Officer",
    "username": "kndlovu2",
    "country": "El Salvador",
    "contact": "(479) 232-9153",
    "email": "kndlovu2@abc.net.au",
    "currentPlan": "Mutare",
    "status": "inactive",
    "avatar": "",
    "avatarColor": "primary",
    "billing": 58
  },
  {
    "id": 4,
    "fullName": "Chipo Dube",
    "company": "Yotz PVT LTD",
    "role": "Agritext Officer",
    "username": "cdube3",
    "country": "El Salvador",
    "contact": "(479) 232-9154",
    "email": "cdube3@abc.net.au",
    "currentPlan": "Gweru",
    "status": "inactive",
    "avatar": "",
    "avatarColor": "primary",
    "billing": 27
  },
  {
    "id": 5,
    "fullName": "Simba Musasa",
    "company": "Yotz PVT LTD",
    "role": "Agritext Officer",
    "username": "_smusasa4",
    "country": "El Salvador",
    "contact": "(479) 232-9155",
    "email": "_smusasa4@abc.net.au",
    "currentPlan": "Masvingo",
    "status": "inactive",
    "avatar": "", 
  	"avatarColor": "primary", 
  	"billing": 71
	},
{
  "id": 6,
  "fullName": "Rudo Mavhunga",
  "company": "Yotz PVT LTD",
  "role": "Agritext Officer",
  "username": "rmavhunga5",
  "country": "El Salvador",
  "contact": "(479) 232-9156",
  "email": "rmavhunga5@abc.net.au",
  "currentPlan": "Kwekwe",
  "status": "inactive",
  "avatar": "",
  "avatarColor": "primary",
  "billing": 64
},
{
     "id": 7,
     "fullName": "Tafadzwa Mlambo",
     "company": "Yotz PVT LTD",
     "role": "Agritext Officer",
     "username": "tmlambo6",
     "country": "El Salvador",
     "contact": "(479) 232 - 9157",
     "email": "tmlambo6 @abc.net.au",
     "currentPlan": "Chinhoyi",
     "status": "inactive",
     "avatar": "",
     "avatarColor": "primary",
     "billing": 19
},
{
     "id": 8,
     "fullName": "Vusimuzi Nyoni",
     "company": "Yotz PVT LTD",
     "role": "Agritext Officer",
     "username": "vnyoni7",
     "country": "El Salvador",
     "contact": "(479) 232 - 9158",
     "email": "vnyoni7 @abc.net.au",
     "currentPlan": "Bindura", 
      "status": "inactive", 
      "avatar": "", 
      "avatarColor": "primary", 
      "billing": 88
}
]
